baseURL: https://abacoaggregate.net/
languageCode: en
title: Abaco Aggregate & Cement Ltd.

upload_dir: static/uploads
public_path: /uploads

disableKinds:
  - taxonomy
  - taxonomyTerm

fields:
- type: field_group_list
  name: slider
  label: Slider
  fields:
  - type: file
    name: slide
    label: Slide
  - type: text
    name: alt
    label: alt